Repository For-The-Dev/Interview-Defence-Go-Client, pull requests merged in 2023-05, with the labels that each got.

#7 🎨 stlye : 레이아웃 + 모달 스타일 변경 + ⚙️setting : npm i --save axios + 폴더 구조 변경 => Mypage
  client/package-lock.json
  client/package.json
  client/src/components/myPage/AnswerDetailModal.style.ts
  client/src/components/myPage/AnswerDetailModal.tsx
  client/src/components/myPage/AnswersPreview.tsx
  client/src/components/myPage/answerPreviewComponent/Content.style.ts
  client/src/components/myPage/answerPreviewComponent/Content.tsx
  client/src/components/myPage/answerPreviewComponent/PageNationContainer.style.ts
  client/src/components/myPage/answerPreviewComponent/PageNationContainer.tsx
  client/src/components/myPage/modalComponent/AnswerBox.style.ts
  client/src/components/myPage/modalComponent/AnswerBox.tsx
  client/src/pages/Layout.tsx
Labels: 🎨 style, ⚙️ setting

#8 230503 머지
  .gitignore
  client/src/components/Accordion.tsx
  client/src/components/GNV.tsx
  client/src/components/SearchInput.tsx
  client/src/components/UserInfomationDropBox.tsx
  client/src/components/myPage/answerPreviewComponent/PageNationContainer.tsx
  client/src/pages/Main.tsx
  client/src/pages/Result.tsx
Labels: ✨ feat

#9 ✨ feat : interviewPage 레이아웃 작업 완료
  client/src/components/interviewPage/InterviewContainer.style.ts
  client/src/components/interviewPage/InterviewContainer.tsx
  client/src/functions/checkInterviewParams.ts
  client/src/pages/Interview.tsx
  client/src/routes/index.tsx
Labels: ✨ feat, 🎨 style

#10 ✨ feat: Login & Logout
  client/.env
  client/src/components/UserInfomationDropBox.tsx
  client/src/pages/Login.tsx
  client/src/pages/Main.tsx
  client/src/routes/index.tsx
Labels: ✨ feat

#12 ✨ feat : react-query 관련 hook 작업
  client/src/apis/index.ts
  client/src/asset/images/Spinner-1s-200px.gif
  client/src/components/GNV.tsx
  client/src/components/SearchInput.tsx
  client/src/components/UserInfomationDropBox.tsx
  client/src/components/common/Loading.style.ts
  client/src/components/common/Loading.tsx
  client/src/components/interviewPage/InterviewContainer.tsx
  client/src/components/myPage/AnswerDetailModal.tsx
  client/src/components/myPage/AnswersPreview.tsx
  client/src/components/myPage/answerPreviewComponent/Content.tsx
  client/src/functions/checkInterviewParams.ts
  client/src/hooks/useGetDetailAnswer.ts
  client/src/hooks/useGetInterview.ts
  client/src/hooks/usePreviewAnwser.ts
  client/src/hooks/useSubmitAnswer.ts
  client/src/hooks/useUser.ts
  client/src/index.tsx
  client/src/pages/Interview.tsx
  client/src/pages/Main.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/Result.tsx
  client/src/react-query/index.ts
  client/src/react-query/queryKey.ts
  client/src/states/stack.ts
Labels: ✨ feat, ⚙️ setting

#13 ✨ feat : interview 페이지 작업완료
  client/src/components/common/Button.tsx
  client/src/components/interviewPage/InterviewContainer.style.ts
  client/src/components/interviewPage/InterviewContainer.tsx
  client/src/components/interviewPage/TimerContainer.stlye.ts
  client/src/components/interviewPage/TimerContainer.tsx
  client/src/components/myPage/AnswerDetailModal.tsx
  client/src/components/myPage/Profile.tsx
  client/src/functions/checkInterviewParams.ts
  client/src/hooks/useGetDetailAnswer.ts
  client/src/hooks/useGetInterview.ts
  client/src/hooks/usePreviewAnwser.ts
  client/src/hooks/useReplytoQuestion.ts
  client/src/hooks/useSubmitAnswer.ts
  client/src/hooks/useUser.ts
  client/src/pages/Interview.tsx
  client/src/pages/ReplyInterview.tsx
  client/src/react-query/queryKey.ts
  client/src/routes/index.tsx
Labels: ✨ feat, 🐛 fix

#14 🔀 merge : 230508 머지
  client/src/asset/images/user.png
  client/src/asset/images/userIcon.png
  client/src/components/Accordion.tsx
  client/src/components/GNB/GNB.style.ts
  client/src/components/GNB/GNB.tsx
  client/src/components/GNB/UserInfomationDropBox.style.ts
  client/src/components/GNB/UserInfomationDropBox.tsx
  client/src/components/GNV.tsx
  client/src/components/SearchInput.tsx
  client/src/components/UserInfomationDropBox.tsx
  client/src/components/mainPage/ConfirmModal.style.ts
  client/src/components/mainPage/ConfirmModal.tsx
  client/src/components/mainPage/SearchInput.style.ts
  client/src/components/mainPage/SearchInput.tsx
  client/src/components/mainPage/Stack.tsx
  client/src/components/resultPage/Accordion.style.ts
  client/src/components/resultPage/Accordion.tsx
  client/src/data/stacks.js
  client/src/data/stacks.ts
  client/src/pages/Layout.tsx
  client/src/pages/LoginPage.tsx
  client/src/pages/Main.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/Result.tsx
  client/src/pages/ResultPage.tsx
  client/src/routes/index.tsx
  client/src/states/mainPage.ts
  client/src/styles/MainPage.style.ts
  client/src/styles/ResultPage.style.ts
Labels: ✨ feat, 🐛 fix, 🎨 style

#19 🐛 fix : 토큰 관련 에러 발생 시 다수의 alert 창 해결, 로그인 여부와 관련된 쿼리 enabled 속성 추가 + ✨ feat : Logo 관련 세팅
  client/public/favicon.ico
  client/public/favicon.svg
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/src/@types/svg.d.ts
  client/src/apis/index.ts
  client/src/asset/images/Main_dark.svg
  client/src/asset/images/Main_light.svg
  client/src/asset/images/Nav_dark.svg
  client/src/asset/images/Nav_light.svg
  client/src/components/GNB/GNB.style.ts
  client/src/components/GNB/GNB.tsx
  client/src/components/GNB/NavLogo.tsx
  client/src/components/mainPage/MainLogo.tsx
  client/src/components/mainPage/SearchInput.style.ts
  client/src/hooks/useCurrentTheme.ts
  client/src/hooks/usePreviewAnwser.ts
  client/src/hooks/useUser.ts
  client/src/pages/MainPage.tsx
  client/src/pages/MyPage.tsx
  client/src/react-query/index.ts
  client/src/styles/MainPage.style.ts
Labels: ✨ feat, 🐛 fix, 🎨 style

#24 ✨ feat : 인증에 따른 라우터 분리 작업 완료
  client/src/App.tsx
  client/src/pages/LoginPage.tsx
  client/src/pages/MyPage.tsx
  client/src/routes/NotFound.tsx
  client/src/routes/PrivateRoute.tsx
  client/src/routes/index.tsx
Labels: ✨ feat, 🐛 fix
