Repository For-The-Dev/Interview-Defence-Go-Client, pull requests merged in 2023-04, with the labels that each got.

#1 ⚙️ setting : theme,router, Layout 세팅 (Layout 추가 수정 필요)
  README.md
  client/package-lock.json
  client/package.json
  client/src/@types/react-app-env.d.ts
  client/src/@types/theme.d.ts
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/pages/Layout.tsx
  client/src/pages/Test.tsx
  client/src/routes/index.tsx
  client/src/states/index.ts
  client/src/styles/reset.ts
  client/src/styles/theme.ts
Labels: ⚙️ setting

#4 mainPage 레이아웃 작업 완료
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/GNV.tsx
  client/src/components/SearchInput.tsx
  client/src/components/UserInfomationDropBox.tsx
  client/src/data/stacks.js
  client/src/image/logoutIcon.png
  client/src/image/loupe.png
  client/src/image/themeIcon.png
  client/src/image/userIcon.png
  client/src/pages/Layout.tsx
  client/src/pages/Main.tsx
  client/src/pages/Result.tsx
  client/src/routes/index.tsx
  client/src/states/stack.ts
Labels: ✨ feat, 🎨 style

#5 Result page
  client/src/components/Accordion.tsx
  client/src/components/SearchInput.tsx
  client/src/components/UserInfomationDropBox.tsx
  client/src/image/aaa.png
  client/src/image/arrow.png
  client/src/pages/Main.tsx
  client/src/pages/Result.tsx
Labels: ✨ feat, 🎨 style

#6 ✨ Feat : MyPage 레이아웃 작업 완료
  client/package-lock.json
  client/package.json
  client/src/@types/index.d.ts
  client/src/asset/.gitkeep
  client/src/asset/images/arrow.png
  client/src/asset/images/github-mark-white.png
  client/src/asset/images/logoutIcon.png
  client/src/asset/images/loupe.png
  client/src/asset/images/themeIcon.png
  client/src/asset/images/userIcon.png
  client/src/components/Accordion.tsx
  client/src/components/SearchInput.tsx
  client/src/components/UserInfomationDropBox.tsx
  client/src/components/common/Button.style.ts
  client/src/components/common/Button.tsx
  client/src/components/myPage/AnswerBox.style.ts
  client/src/components/myPage/AnswerBox.tsx
  client/src/components/myPage/AnswerDetailModal.style.ts
  client/src/components/myPage/AnswerDetailModal.tsx
  client/src/components/myPage/AnswersPreview.style.ts
  client/src/components/myPage/AnswersPreview.tsx
  client/src/components/myPage/Content.style.ts
  client/src/components/myPage/Content.tsx
  client/src/components/myPage/PageNationContainer.style.ts
  client/src/components/myPage/PageNationContainer.tsx
  client/src/components/myPage/Profile.style.ts
  client/src/components/myPage/Profile.tsx
  client/src/image/aaa.png
  client/src/pages/Layout.tsx
  client/src/pages/MyPage.tsx
  client/src/routes/index.tsx
  client/src/styles/theme.ts
  client/tsconfig.json
Labels: ✨ feat
